### ISSUE TITLE
Secret Options in Sessions

### ISSUE THREAD

**Issue by arthursgonzaga** [aleffaso/LogInAndLogOut#1]
Hi, Aleff,

When I test the project, I have this issue:

```
Error: secret option required for sessions
    at session (/Users/arthur/Desktop/LogInAndLogOut/node_modules/express-session/index.js:200:12)
    at Layer.handle [as handle_request] (/Users/arthur/Desktop/LogInAndLogOut/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/arthur/Desktop/LogInAndLogOut/node_modules/express/lib/router/index.js:323:13)
    at /Users/arthur/Desktop/LogInAndLogOut/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/arthur/Desktop/LogInAndLogOut/node_modules/express/lib/router/index.js:341:12)
    at next (/Users/arthur/Desktop/LogInAndLogOut/node_modules/express/lib/router/index.js:275:10)
    at /Users/arthur/Desktop/LogInAndLogOut/node_modules/express-flash/lib/express-flash.js:31:7
    at /Users/arthur/Desktop/LogInAndLogOut/node_modules/connect-flash/lib/flash.js:21:5
    at /Users/arthur/Desktop/LogInAndLogOut/node_modules/express-flash/lib/express-flash.js:22:5
    at Layer.handle [as handle_request] (/Users/arthur/Desktop/LogInAndLogOut/node_modules/express/lib/router/layer.js:95:5)
```

How I can resolve this problem? When resolved, I suggest increment in README file for future testers.

**Comment by aleffaso** [comment]
Don't forget to put `SESSION_SECRET = secret` on .env file

**Comment by arthursgonzaga** [comment]
Thanks, this works fine.
